#define CYCLES_PER_SECOND 7.16e6
#define CYCLES_PER_FRAME 119665
#define CYCLES_PER_HBLANK 79
#define REFRESH_RATE (CYCLES_PER_SECOND / CYCLES_PER_FRAME)
#define CYCLES_PER_SCANLINE 455
#define TOTAL_SCANLINES (CYCLES_PER_FRAME / CYCLES_PER_SCANLINE)
#define CYCLES_BEFORE_VBLANK 118300
#define CYCLES_PER_VBLANK 1365

#define SAMPLE_BUFFER_SIZE 1024
#define SAMPLE_RATE 44100
#define AUDIO_PUSH_RATE (CYCLES_PER_SECOND / SAMPLE_RATE)